version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passhihihi
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - urlshortener_pgdata:/var/lib/postgresql/data
        
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: urlshortener-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  urlshortener_pgdata: